### ISSUE TITLE
fluentd::conf_dir unmanaged file should be purged

### ISSUE THREAD

**Issue by lzecca78** [wywygmbh/puppet-fluentd#14]
In the definition of the directory written here : 

https://github.com/wywygmbh/puppet-fluentd/blob/master/manifests/config.pp#L13-L18

should be really useful if the file type can delete unmanaged fluentd conf files: 

```
  file { $::fluentd::conf_dir:
    ensure => 'directory',
    purge   => true,
    recurse => true.
    owner  => $::fluentd::user_name,
    group  => $::fluentd::user_group,
    mode   => '0750',
  }```

**Comment by Moozaliny** [comment]
would you mind to create a pull request for this? 
`purge` and `recurse` should be configurable with parameters and default to false, to don't break existing setups.

**Comment by lzecca78** [comment]
Hi @Moozaliny, i just opened a pull request setting a default class parameter to `false` in order to be backward compatible. Let me know if there is something wrong.

**Comment by Moozaliny** [comment]
@lzecca78 your pull request has been merged and is deployed to puppet forge. Thanks!
